# frontend/Dockerfile.dev
FROM node:22

WORKDIR /app

# Install dependencies
COPY package*.json ./
RUN npm ci

# Copy everything
COPY . .

# Expose default Angular dev server port
EXPOSE 4200

# Use ng serve with host 0.0.0.0 so it's reachable from host machine
CMD ["npm", "run", "start", "--", "--host", "0.0.0.0", "--port", "4200"]
