# frontend/nginx.conf
# Nginx configuration for serving Angular frontend application
server {
    listen 80;

    # Serve static files
    root /usr/share/nginx/html;
    index index.html;

    # Angular SPA routing
    location / {
        try_files $uri /index.html;
    }
}
