/** @type {import('tailwindcss').Config} */
module.exports = {
  content: [
    './src/**/*.{html,ts}',
  ],
  darkMode: 'class',
  theme: {
    extend: {
      colors: {
        "background": "#f8f9ff",
        "tertiary-fixed": "#a6f4b5",
        "on-primary-fixed": "#001b3d",
        "secondary-fixed": "#d5e3fc",
        "secondary": "#515f74",
        "on-surface-variant": "#424752",
        "inverse-primary": "#a8c8ff",
        "tertiary-container": "#216d3b",
        "surface-tint": "#005db5",
        "surface-container-highest": "#d3e4fe",
        "on-secondary-container": "#57657a",
        "surface-container-low": "#eff4ff",
        "on-primary-fixed-variant": "#00468b",
        "error-container": "#ffdad6",
        "on-error": "#ffffff",
        "outline": "#727783",
        "tertiary": "#005427",
        "surface-container-lowest": "#ffffff",
        "on-tertiary": "#ffffff",
        "on-tertiary-container": "#9fecad",
        "tertiary-fixed-dim": "#8bd79b",
        "on-primary": "#ffffff",
        "surface": "#f8f9ff",
        "on-secondary": "#ffffff",
        "surface-bright": "#f8f9ff",
        "primary-fixed": "#d6e3ff",
        "secondary-fixed-dim": "#b9c7df",
        "outline-variant": "#c2c6d4",
        "error": "#ba1a1a",
        "surface-variant": "#d3e4fe",
        "primary-container": "#005fb8",
        "surface-container": "#e5eeff",
        "on-tertiary-fixed-variant": "#005226",
        "surface-dim": "#cbdbf5",
        "primary-fixed-dim": "#a8c8ff",
        "on-background": "#0b1c30",
        "inverse-on-surface": "#eaf1ff",
        "on-surface": "#0b1c30",
        "on-secondary-fixed": "#0d1c2e",
        "on-error-container": "#93000a",
        "inverse-surface": "#213145",
        "secondary-container": "#d5e3fc",
        "surface-container-high": "#dce9ff",
        "on-primary-container": "#cadcff",
        "primary": "#00488d",
        "on-secondary-fixed-variant": "#3a485b",
        "on-tertiary-fixed": "#00210b"
      },
      fontFamily: {
        "headline": ["Manrope", "system-ui", "sans-serif"],
        "body": ["Inter", "system-ui", "sans-serif"],
        "label": ["Inter", "system-ui", "sans-serif"]
      },
      borderRadius: {
        "DEFAULT": "0.25rem",
        "lg": "0.5rem",
        "xl": "0.75rem",
      },
    },
  },
  plugins: [],
}
