# docker-compose.dev.yml
version: "3.8"

services:
  backend-api:
    build:
      context: ./backend/TimeManagerApi
      dockerfile: Dockerfile.dev
    container_name: tmf-backend-api-dev
    volumes:
      - ./backend/TimeManagerApi:/src
    ports:
      - "5052:5052"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    networks:
      - tmf-net

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile.dev
    container_name: tmf-frontend-dev
    volumes:
      - ./frontend:/app
      - /app/node_modules
    ports:
      - "4200:4200"
    depends_on:
      - backend-api
    networks:
      - tmf-net

networks:
  tmf-net:
    driver: bridge
